apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      containers:
        - name: testing-app
          image: spaghettic0der/testing-app-pipeline:1.0.0-20
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
