apiVersion: v1
kind: Service
metadata:
  name: testing-app-service
  labels:
    app: testing-app 
spec:
  selector:
    app: testing-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
